// <auto-generated />
using System;
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.5.23280.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Account", b =>
                {
                    b.Property<string>("IdUser")
                        .HasColumnType("char(5")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_name");

                    b.HasKey("IdUser");

                    b.ToTable("tb_m_account");
                });

            modelBuilder.Entity("API.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("deskripsi");

                    b.Property<string>("NamaKategori")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nm_kategori");

                    b.HasKey("Id");

                    b.ToTable("tb_m_kategori");
                });

            modelBuilder.Entity("API.Models.Komentar", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(100)")
                        .HasColumnName("id_komen");

                    b.Property<string>("IsiKomentar")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("isi_komentar");

                    b.Property<DateTime>("TanggalKomentar")
                        .HasColumnType("datetime")
                        .HasColumnName("tgl_komentar");

                    b.HasKey("Id");

                    b.ToTable("tb_m_komentar");
                });

            modelBuilder.Entity("API.Models.Resep", b =>
                {
                    b.Property<string>("IdResep")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("resep_id");

                    b.Property<string>("Bahan")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("bahan");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("deskripsi");

                    b.Property<string>("Jumlah")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("jumlah");

                    b.Property<string>("Kesulitan")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("kesulitan");

                    b.Property<string>("NamaResep")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nm_resep");

                    b.Property<string>("Satuan")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("satuan");

                    b.Property<string>("WaktuMemasak")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("wkt_memasak");

                    b.Property<string>("WaktuPersiapan")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("wkt_persiapan");

                    b.HasKey("IdResep");

                    b.ToTable("tb_m_resep");
                });
#pragma warning restore 612, 618
        }
    }
}
